### ISSUE TITLE
'TypeError: tryCatchTarget.apply is not a function' when trying to use `windowWhen`

### ISSUE THREAD

**Issue by LukaJCB** [jasonzoladz/purescript-rxjs#6]
Full stacktrace: 

TypeError: tryCatchTarget.apply is not a function
    at tryCatcher (/Users/luka/proj/purescript-rxjs/node_modules/rxjs/util/tryCatch.js:6:31)
    at WindowSubscriber.openWindow (/Users/luka/proj/purescript-rxjs/node_modules/rxjs/operator/windowWhen.js:115:72)
    at new WindowSubscriber (/Users/luka/proj/purescript-rxjs/node_modules/rxjs/operator/windowWhen.js:74:14)
    at WindowOperator.call (/Users/luka/proj/purescript-rxjs/node_modules/rxjs/operator/windowWhen.js:59:33)
    at Observable.subscribe (/Users/luka/proj/purescript-rxjs/node_modules/rxjs/Observable.js:42:22)
    at /Users/luka/proj/purescript-rxjs/output/RxJS.Observable/foreign.js:38:11
    at __do (/Users/luka/proj/purescript-rxjs/output/Test.Main/index.js:30:57)
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:269:16
    at /Users/luka/proj/purescript-rxjs/output/Test.Unit/foreign.js:23:7
    at /Users/luka/proj/purescript-rxjs/output/Control.Monad.Aff/foreign.js:214:12

**Comment by LukaJCB** [comment]
Turns out `windowWhen` expects a `() -> Observable a` instead of just an `Observable a`, so fixing it in either `Observable.js` or `Observable.purs` should do the trick. Maybe make it a `Lazy (Observable a)`?

**Comment by jasonzoladz** [comment]
Fixed by #10
